use numberOne

insert into song values
('Independent Women'),
('It Wasnt Me'),
('Ms. Jackson'),
('Stutter'),
('Butterfly'),
('Angel'),
('All for You'),
('Lady Marmalade'),
('U Remind Me'),
('Bootylicious'),
('Fallin'),
('Im Real (Murder Remix)'),
('Family Affair'),
('U Got It Bad'),
('How You Remind Me'),
('Always on Time'),
('Aint It Funny (Murder Remix)'),
('Foolish'),
('Hot in Herre'),
('Dilemma'),
('A Moment Like This'),
('Lose Yourself'),
('Bump, Bump, Bump'),
('All I Have'),
('In da Club'),
('Get Busy'),
('21 Questions'),
('This Is the Night'),
('Crazy in Love'),
('Shake Ya Tailfeather'),
('Baby Boy'),
('Stand Up'),
('Hey Ya!'),
('The Way You Move'),
('Slow Jamz'),
('Yeah!'),
('Burn'),
('I Believe'),
('Confessions Part II'),
('Slow Motion'),
('Lean Back'),
('Goodies'),
('My Boo'),
('Drop It Like Its Hot'),
('Let Me Love You'),
('Candy Shop'),
('Hollaback Girl'),
('We Belong Together'),
('Inside Your Heaven'),
('Gold Digger'),
('Run It!'),
('Dont Forget About Us'),
('Laffy Taffy'),
('Grillz'),
('Check on It'),
('Youre Beautiful'),
('So Sick'),
('Temperature'),
('Bad Day'),
('SOS'),
('Ridin'),
('Hips Dont Lie'),
('Do I Make You Proud'),
('Promiscuous'),
('London Bridge'),
('SexyBack'),
('Money Maker'),
('My Love'),
('I Wanna Love You'),
('Irreplaceable'),
('Say It Right'),
('What Goes Around...Comes Around'),
('This Is Why Im Hot'),
('Glamorous'),
('Dont Matter'),
('Give It to Me'),
('Girlfriend'),
('Makes Me Wonder'),
('Buy U a Drank (Shawty Snappin)'),
('Umbrella'),
('Hey There Delilah'),
('Beautiful Girls'),
('Big Girls Dont Cry'),
('Crank That (Soulja Boy)'),
('Stronger'),
('Kiss Kiss'),
('No One'),
('Low'),
('Love in This Club'),
('Bleeding Love'),
('Touch My Body'),
('Lollipop'),
('Take a Bow'),
('Viva la Vida'),
('I Kissed a Girl'),
('Disturbia'),
('Whatever You Like'),
('So What'),
('Live Your Life'),
('Womanizer'),
('Single Ladies (Put a Ring on It)'),
('Just Dance'),
('My Life Would Suck Without You'),
('Crack a Bottle'),
('Right Round'),
('Poker Face'),
('Boom Boom Pow'),
('I Gotta Feeling'),
('Down'),
('3'),
('Fireflies'),
('Whatcha Say'),
('Empire State of Mind'),
('Tik Tok'),
('Imma Be'),
('Break Your Heart'),
('Rude Boy'),
('Nothin on You'),
('OMG'),
('Not Afraid'),
('California Gurls'),
('Love the Way You Lie'),
('Teenage Dream'),
('Just the Way You Are'),
('Like a G6'),
('We R Who We R'),
('Whats My Name?'),
('Only Girl (In the World)'),
('Raise Your Glass'),
('Firework'),
('Grenade'),
('Hold It Against Me'),
('Black and Yellow'),
('Born This Way'),
('E.T.'),
('S&M'),
('Rolling in the Deep'),
('Give Me Everything'),
('Party Rock Anthem'),
('Last Friday Night (T.G.I.F.)'),
('Moves Like Jagger'),
('Someone Like You'),
('We Found Love'),
('Sexy and I Know It'),
('Set Fire to the Rain'),
('Stronger (What Doesnt Kill You)'),
('Part of Me'),
('We Are Young'),
('Somebody That I Used to Know'),
('Call Me Maybe'),
('Whistle'),
('We Are Never Ever Getting Back Together'),
('One More Night'),
('Diamonds'),
('Locked Out of Heaven'),
('Thrift Shop[4]'),
('Harlem Shake'),
('When I Was Your Man'),
('Just Give Me a Reason'),
('Cant Hold Us'),
('Blurred Lines'),
('Roar'),
('Wrecking Ball'),
('Royals'),
('The Monster'),
('Timber'),
('Dark Horse'),
('Happy[1]'),
('All of Me'),
('Fancy'),
('Rude'),
('Shake It Off'),
('All About That Bass'),
('Blank Space'),
('Uptown Funk'),
('See You Again'),
('Bad Blood'),
('Cheerleader'),
('Cant Feel My Face'),
('What Do You Mean?'),
('The Hills'),
('Hello'),
('Sorry'),
('Love Yourself'),
('Pillowtalk'),
('Work'),
('Panda'),
('One Dance'),
('Cant Stop the Feeling!'),
('Cheap Thrills'),
('Closer'),
('Black Beatles'),
('Starboy'),
('Bad and Boujee'),
('Shape of You'),
('Humble'),
('Thats What I Like'),
('Im the One'),
('Despacito'),
('Look What You Made Me Do'),
('Bodak Yellow'),
('Rockstar'),
('Perfect'),
('Havana'),
('Gods Plan'),
('Nice for What'),
('This Is America'),
('Psycho'),
('Sad!'),
('I Like It'),
('In My Feelings'),
('Girls Like You'),
('Thank U, Next'),
('Sicko Mode'),
('Without Me'),
('Sunflower'),
('7 Rings'),
('Shallow'),
('Sucker'),
('Old Town Road'),
('Bad Guy'),
('Señorita'),
('Truth Hurts'),
('Highest in the Room'),
('Someone You Loved'),
('Lose You to Love Me'),
('Circles'),
('Heartless'),
('All I Want for Christmas Is You'),
('The Box'),
('Blinding Lights'),
('Toosie Slide'),
('The Scotts'),
('Say So'),
('Stuck with U'),
('Savage'),
('Rain on Me'),
('Trollz'),
('Cardigan'),
('Watermelon Sugar'),
('WAP'),
('Dynamite'),
('Franchise'),
('Savage Love (Laxed – Siren Beat)'),
('Mood'),
('Positions'),
('Life Goes On'),
('Willow'),
('Drivers License'),
('Whats Next'),
('Up'),
('Peaches'),
('Montero (Call Me by Your Name)'),
('Leave the Door Open'),
('Rapstar'),
('Save Your Tears'),
('Good 4 U'),
('Butter'),
('Permission to Dance'),
('Stay'),
('Way 2 Sexy'),
('My Universe'),
('Industry Baby'),
('Easy on Me'),
('All Too Well (Taylors Version)'),
('We Dont Talk About Bruno'),
('Heat Waves'),
('As It Was'),
('First Class'),
('Wait for U'),
('Jimmy Cooks'),
('About Damn Time'),
('Break My Soul'),
('Super Freaky Girl'),
('Bad Habit'),
('Unholy'),
('Anti-Hero'),
('Flowers'),
('Die for You'),
('Last Night'),
('Like Crazy'),
('Kill Bill'),
('Vampire'),
('Seven'),
('Try That in a Small Town'),
('Rich Men North of Richmond'),
('I Remember Everything'),
('Paint the Town Red'),
('Slime You Out'),
('First Person Shooter'),
('Cruel Summer'),
('Is It Over Now?'),
('Lovin on Me'),
('Rockin Around the Christmas Tree'),
('Yes, And?'),
('Hiss'),
('Texas Hold Em'),
('Carnival'),
('We Cant Be Friends (Wait for Your Love)'),
('Lose Control'),
('Like That'),
('Too Sweet'),
('Fortnight'),
('Not Like Us'),
('I Had Some Help'),
('Please Please Please'),
('A Bar Song (Tipsy)'),
('Love Somebody'),
('Squabble Up'),
('Die with a Smile'),
('4x4'),
('Luther'),
('What I Want'),
('Ordinary'),
('Manchild'),
('Golden'),
('The Fate of Ophelia')
