use numberOne

insert into artist values

('Destinys Child'),
('Shaggy'),
('OutKast'),
('Joe'),
('Crazy Town'),
('Janet'),
('Christina Aguilera'),
('Usher'),
('Alicia Keys'),
('Jennifer Lopez'),
('Mary J. Blige'),
('Nickelback'),
('Ja Rule'),
('Ashanti'),
('Nelly'),
('Kelly Clarkson'),
('Eminem'),
('B2K'),
('50 Cent'),
('Sean Paul'),
('Beyoncé'),
('Ludacris'),
('Twista'),
('Fantasia'),
('Juvenile'),
('Terror Squad'),
('Ciara'),
('Snoop Dogg'),
('Mario'),
('Gwen Stefani'),
('Mariah Carey'),
('Carrie Underwood'),
('Kanye West'),
('Chris Brown'),
('D4L'),
('James Blunt'),
('Ne-Yo'),
('Daniel Powter'),
('Rihanna'),
('Chamillionaire'),
('Shakira'),
('Taylor Hicks'),
('Nelly Furtado'),
('Fergie'),
('Justin Timberlake'),
('Akon'),
('Mims'),
('Timbal'),
('Avril Lavigne'),
('Maroon 5'),
('T-Pain'),
('Plain White Ts'),
('Sean Kingston'),
('Soulja Boy Tell Em'),
('Flo Rida'),
('Leona Lewis'),
('Lil Wayne'),
('Coldplay'),
('Katy Perry'),
('T.I.'),
('Pink'),
('Britney Spears'),
('Lady Gaga'),
('The Black Eyed Peas'),
('Jay Sean'),
('Owl City'),
('Jason Derulo'),
('Jay-Z'),
('Kesha'),
('Taio Cruz'),
('B.o.B'),
('Bruno Mars'),
('Far East Movement'),
('Wiz Khalifa'),
('Adele'),
('Pitbull'),
('LMFAO'),
('Fun'),
('Gotye'),
('Carly Rae Jepsen'),
('Taylor Swift'),
('Macklemore & Ryan Lewis'),
('Baauer'),
('Robin Thicke'),
('Miley Cyrus'),
('Lorde'),
('Pharrell Williams'),
('John Legend'),
('Iggy Azalea'),
('Magic!'),
('Meghan Trainor'),
('Mark Ronson'),
('Omi'),
('The Weeknd'),
('Justin Bieber'),
('Zayn'),
('Desiigner'),
('Drake'),
('Sia'),
('The Chainsmokers'),
('Rae Sremmurd'),
('Migos'),
('Ed Sheeran'),
('Kendrick Lamar'),
('DJ Khaled'),
('Chance the Rapper'),
('Luis Fonsi'),
('Cardi B'),
('Post Malone'),
('Camila Cabello'),
('Childish Gambino'),
('XXXTentacion'),
('Ariana Grande'),
('Travis Scott'),
('Halsey'),
('Jonas Brothers'),
('Lil Nas X'),
('Billie Eilish'),
('Shawn Mendes'),
('Lizzo'),
('Lewis Capaldi'),
('Selena Gomez'),
('Roddy Ricch'),
('The Scotts'),
('Doja Cat'),
('Megan Thee Stallion'),
('DaBaby'),
('6ix9ine'),
('Harry Styles'),
('BTS'),
('Jawsh 685'),
('24kGoldn'),
('Olivia Rodrigo'),
('Silk Sonic'),
('Polo G'),
('The Kid Laroi'),
('Carolina Gaitán'),
('Rhenzy Feliz'),
('Glass Animals'),
('Jack Harlow'),
('Future'),
('Nicki Minaj'),
('Steve Lacy'),
('Sam Smith'),
('Morgan Wallen'),
('Jimin'),
('SZA'),
('Jung Kook'),
('Jason Aldean'),
('Oliver Anthony Music'),
('Zach Bryan'),
('Brenda Lee'),
('¥$'),
('Teddy Swims'),
('Hozier'),
('Sabrina Carpenter'),
('Shaboozey'),
('Alex Warren'),
('Huntrix'),
('Clay Aiken')

